public class FoodManager{
    private List<Food> Stock;
    private IngredientDatabase Ingredients;

    public FoodManager()
    {
        String path = "";
    }

    public void addIngredient(Ingredient ingredient)
    {

    }

    public void createRecipe()
    {

    }

    public void createMeal()
    {

    }

    public void subtractIngredient(Ingredient ingredient, int amount)
    {

    }

    public List<String> createShoppingList()
    {

    }

    public List<String> getRecommendedShoppingList()
    {

    }

    public List<String> getRecommendedShoppingList(Recipe recipe)
    {

    }

    public Ingredient getIngredient(String name)
    {

    }

    public String[] getMealInstructions()
    {
        
    }


}